# Generated by Django 3.0.2 on 2020-02-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(choices=[('Erkek', ' 1'), ('Kadın', '0')], max_length=15)),
                ('Cp', models.IntegerField(choices=[('0', ' 0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=0)),
                ('Trestbps', models.IntegerField(default=0)),
                ('Chol', models.IntegerField(default=0)),
                ('Fbs', models.IntegerField(choices=[('0', '0'), ('1', '1')], default=0)),
                ('Restecg', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default=0)),
                ('Thalach', models.IntegerField(default=0)),
                ('Exang', models.CharField(choices=[('Evet', '1'), ('Hayır', '0')], max_length=15)),
                ('Oldpeak', models.IntegerField(default=0)),
                ('Slope', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default=0)),
                ('Ca', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=0)),
                ('Thal', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], default=0)),
            ],
        ),
    ]
